project:
  type: website
  output-dir: docs
  resources: CNAME

website:
  title: "CV med Lab"
  site-url: https://cvmedlab.org/
  repo-url: https://github.com/cvmedlab/cvmedlab.github.io/
  google-analytics: G-K32ECMZR0R
  navbar:
    title: "{CVmedLab}"
    left:
      - text: "about"
        href: about.qmd
      - text: "people"
        href: people.qmd
      - text: "research"
        href: research.qmd
      - text: "papers"
        href: papers.qmd
      - text: "tools"
        href: https://github.com/ssmithm?tab=repositories
      - text: "lab docs"
        menu:
          - text: "Table 1 {R}"
            href: labdocs/table1_gtsummary.qmd
          - text: "Cumulative Incidence Curves {R}"
            href: labdocs/cumulative_incidence.qmd
          - text: "Forest Plot {R}"
            href: labdocs/forest_plot.qmd
          - text: "Scientific Writing" 
            href: labdocs/writing.qmd
      - text: "lab manual"
        href: https://labmanual.cvmedlab.org/

    right:
      - icon: github
        href: https://github.com/cvmedlab
      - icon: twitter
        href: https://twitter.com/CVmedLab

  #page-footer: "Copyright 2022, Steven M. Smith" 
  
format:
  html:
    theme: [default, custom.scss] 

editor: visual

