---
format: 
  html:
    include-in-header: 
      - ../../include/icons.html
resources:
  - "ATC4_drugs.xlsx"
---

## [High-throughput Screening for Antihypertensive Prescribing Cascades]{style="color: #1E354B"}

#### Funder

[National Heart, Lung and Blood Institute](https://nhlbi.nih.gov/)

#### Award

R21 HL159576

#### PI(s)

Steven Smith

#### Funding Period

July 2022 - June 2024

#### Overview

Hypertension (HTN) is prevalent in nearly half of U.S. adults and treated with \>3 million antihypertensive prescription fills per day in the U.S. Although commonly-used antihypertensives are generally well-tolerated, their ubiquitous use exposes millions of adults to potentially treatment-limiting adverse events (AEs), some of which are well-known, but many are non-specific or indistinguishable from HTN-related symptoms and not easily attributed to the offending antihypertensive. Failure to associate these AEs with the causative agent may prompt additional therapy to treat the AE—known as a “prescribing cascade”—with potentially important implications regarding polypharmacy, unnecessary costs, exposure to additional side effects, treatment nonadherence, and reduced quality of life, especially in older adults. Most prescribing cascade studies to date have been narrowly focused on drugs with a well-known AE that is highly specific to the drug, severely limiting our understanding of prescribing cascades occurring due to less well-known or non-specific AEs. This approach has resulted in slow knowledge generation and missed opportunities for comprehensively assessing and discovering new prescribing cascades. In line with NHLBI Strategic Objective 7 to “leverage emerging opportunities in data science to open new frontiers in research,” this proposal seeks to develop and utilize a novel methodologic approach for high-throughput screening of prescribing cascades and discover novel antihypertensive prescribing cascades using a nationally-representative administrative claims data source. This goal will be achieved via the following Aims: 1) elucidate candidate antihypertensive-related prescribing cascades using the SIDe Effect Resource, a collection of prescription labeling which include drug AEs and drug indications; 2) identify prescribing cascade signals occurring during real world use of antihypertensives using a Medicare database; and, 3) classify cascade signal detection and prioritize further research via an expert panel. The proposed work is expected to 1) identify and characterize the magnitude of common antihypertensive prescribing cascades, including those previously unknown; 2) develop an efficient framework for wide-scale assessment of prescribing cascade detection; and, 3) establish the basis for a compendium of known cascades. This proposal also builds logically towards future research applying this framework for discovery of prescribing cascades with cardiovascular (and other) treatments, assessing downstream consequences of prescribing cascades, and testing clinical decision support aids to prevent prescribing cascades.

#### Associated Manuscripts

1.  Wang GH, et al. Modifiable statin characteristics associated with potential statin-related prescribing cascades. Pharmacotherapy 2023;43(12):1307-16. doi: [10.1002/phar.2883](https://doi.org/10.1002/phar.2883). PubMed PMID: [37771303](https://pubmed.ncbi.nlm.nih.gov/37771303/).

2.  Vouri SM, et al. High-throughput screening for prescribing cascades among real world statin initiators. Pharmacoepidemiol Drug Saf 2023;32(7):773-82. doi: [10.1002/pds.5607](https://doi.org/10.1002/pds.5607). PubMed PMID: [36880251](https://pubmed.ncbi.nlm.nih.gov/36880251/).

3.  Wang GH, et al. Continued potassium supplementation use following loop diuretic discontinuation in older adults: An evaluation of a prescribing cascade relic. J Am Geriatr Soc 2023;71(2):505-15. doi: [10.1111/jgs.18103](https://doi.org/10.1111/jgs.18103). PubMed PMID: [36289555](https://pubmed.ncbi.nlm.nih.gov/36289555/).

4.  Vouri SM, et al. Evaluation of a Beta-Blocker-Edema-Loop Diuretic Prescribing Cascade: A Prescription Sequence Symmetry Analysis Am J Hypertens 2022;35(7):601-9. doi: [10.1093/ajh/hpac013](https://doi.org/10.1093/ajh/hpac013). PubMed PMID: [35106529](https://pubmed.ncbi.nlm.nih.gov/35106529/).

#### Associated Resources

-   [Statin Prescribing Cascades High-throughput Screening Visualizations](https://public.tableau.com/app/profile/cvmedlab/viz/Resultsofthehigh-throughputSSAscreening/TableofContentsFlowchart)

-   [Antihypertensive ATC4 List](./ATC4_drugs.xlsx)
