---
format: 
  html:
    include-in-header: 
      - ../../include/icons.html
---

## [BP Telehealth]{style="color: #1E354B"}

#### Funder

[National Heart, Lung and Blood Institute](https://nhlbi.nih.gov/)

#### Award

1R01HL171387

#### PI(s)

Steven Smith, [Mark Pletcher (UCSF)](https://profiles.ucsf.edu/mark.pletcher)

#### Funding Period

March 2025 - December 2029

#### Overview

Uncontrolled blood pressure (BP) is the most prevalent modifiable risk for cardiovascular disease (CVD) and disorders directly influencing CVD (e.g., diabetes, chronic kidney disease, etc.). Along with many other aspects of U.S. healthcare, management of uncontrolled BP was severely disrupted during the COVID-19 pandemic. In response, many health systems rapidly accelerated implementation of new technologies, including telehealth visits for BP control and support for self-monitoring with home-based measurement of BP. Anecdotally, new BP control technologies and strategies have been implemented differentially with wide variation in timing and degree of utilization, but systematic analyses showing the extent and variability of implementation across sites are lacking. Meanwhile, substantial and variable backsliding in BP control rates across health systems was documented at the onset of the pandemic, and it is unclear how much of the variability is driven by differential implementation of new BP-related technologies and strategies.

To learn from this unprecedented natural experiment and help guide the US healthcare enterprise towards more effective and equitable practices for management of BP control, we are conducting a mixed methods comparative effectiveness analysis. We leverage our nationally scoped PCORnet Blood Pressure Control Laboratory (BPCL) – designed fundamentally for efficient surveillance of BP control and related process metrics using electronic health record (EHR) data – to develop and validate process metric queries that track implementation of new BP-related technologies & strategies, field these queries along with our previously developed metrics, extract trend results and individual patient-level data from participating sites, and conduct descriptive and causal inference analyses to decipher successful patterns of care for uncontrolled BP. In addition, we are conducting a positive deviance analysis with mixed methods approach to assess residual variability in BP control across clinics and learn from clinics with unexplained excellence.

The specific aims of this project are to:

1.  **Evaluate time trends and disparities in utilization of BP-related telehealth and home BP monitoring.**

2.  **Estimate causal effects of telehealth implementation on BP control and related metrics in hypertension management.**

3.  **Identify clinics with unexplained resilience in BP control and use mixed methods to analyze potential mechanisms and opportunities for dissemination of effective, scalable practices.**

As we have done in prior work, we will test for effect heterogeneity across important subgroups (sex, race, ethnicity) and place special emphasis on BP control in non-Hispanic Black patients, for whom disparities are historically largest. Findings from these aims will be discussed with stakeholders via webinar including a panel of frontline clinicians and leaders from positive deviant clinical sites, and disseminated via conference presentations and publications.

#### Lab Members Working on this Project

Shailina Keshwani, PhD

Asinamai Ndai, MS

Tram Nguyen, MS

#### Associated Manuscripts